spring:
  application:
    name: clothes
  data:
    mongodb:
      uri: mongodb://localhost:27017/clothes
  security:
    user:
      name: admin
      password: admin
  cloudinary:
    cloud_name: dpl6qaj9m
    api_key: 155838669771664
    api_secret: v6JfO11VIZFhK2ONNyJvFMbKUIU
  custom:
    predict_url: http://longtch.id.vn/python/predict