spring:
  application:
    name: clothes
  data:
    mongodb:
      database: clothes
      host: localhost
      port: 27017
      auto-index-creation: true
  security:
    user:
      name: admin
      password: admin

